[build]
  publish = "static"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/predict"
  to = "/.netlify/functions/predict"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/auth/token"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/predict"
  to = "/.netlify/functions/predict"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
